on:
  push:
    branches: master

name: Deploy to Google Compute Engine

jobs:
  deploy:
    name: Deploy to Google Compute Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          dockerfile: backend/Dockerfile
          name: ${{ secrets.DOCKERHUB_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Google Cloud Auth
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Google Compute Engine Update
        uses: actions/gcloud/cli@master
        with:
          args: --quiet compute instances update-container ${{ secrets.GCE_INSTANCE }}

  coverage:
    name: Test Coverage Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Unit tests and go vet
        uses: cedrickring/golang-action@1.3.0
        env:
          PROJECT_PATH: "./backend"
          GO111MODULE: "on"
          IMPORT: "r-cbb/cbbpoll"

      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./backend/coverage.out
          flags: unittests
          name: cbbpoll-unittests